const types = {
  FEATURES_PRODUCT_CARD: "FEATURES_PRODUCT_CARD",
  SMALL_PRODUCT_CARD: "SMALL_PRODUCT_CARD",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  DELETE: "DELETE",
  UPDATE: "UPDATE",
};

export default types;
